const initialCatalog = [
    {
      id: 1,
      name: 'CHAMPION-CREWNECK T-SHIRT Men',
      price: 1478,
      image: './img/cp1.jpg',
      details: 'เสื้อยืดทีเชิ้ตสำหรับผู้ชาย แบรนด์ CHAMPION',
      SKU: '218632-WW007',
      type: 'T-SHIRT',
      Brand: 'CHAMPION',
      gender: 'Men',
    },
    {
      id: 2,
      name: 'CHAMPION-CREWNECK T-SHIRT Men',
      price: 1478,
      image: './img/cp2.jpg',
      details: 'เสื้อยืดทีเชิ้ตสำหรับผู้ชาย แบรนด์ CHAMPION',
      SKU: '218631-VS048',
      type: 'T-SHIRT',
      Brand: 'CHAMPION',
      gender: 'Men',
    },
    {
      id: 3,
      name: 'CHAMPION-CREWNECK T-SHIRT Men',
      price: 1106,
      image: './img/cp3.jpg',
      details: 'เสื้อยืดทีเชิ้ตสำหรับผู้ชาย แบรนด์ CHAMPION',
      SKU: '218531-BS501',
      type: 'T-SHIRT',
      Brand: 'CHAMPION',
      gender: 'Men',
    },
    {
      id: 4,
      name: 'CHAMPION-SLEEVELESS CREWNECK T-SHIRT Men',
      price: 920,
      image: './img/cp4.jpg',
      details: 'เสื้อยืดทีเชิ้ตสำหรับผู้ชาย แบรนด์ CHAMPION',
      SKU: '218532-BS501',
      type: 'TANK',
      Brand: 'CHAMPION',
      gender: 'Men',
    },
    {
      id: 5,
      name: 'CHAMPION-BERMUDA Men',
      price: 795,
      image: './img/cp5.jpg',
      details: 'กางเกงบาสเก็ตบอล แบรนด์ Champion',
      SKU: '215927-BS508',
      type: '	APPAREL',
      Brand: 'CHAMPION',
      gender: 'Men',
    },

  {
    id: 6,
    name: 'CHAMPION-BERMUDA Men',
    price: 795,
    image: './img/cp6.jpg',
    details: 'กางเกงบาสเก็ตบอล แบรนด์ Champion',
    SKU: '215922-KK001',
      type: 'APPAREL',
      Brand: 'CHAMPION',
      gender: 'Men',
  },
];
  
  export default initialCatalog;
  